export enum CampaignEnum {
  ALL = 0,
  NEW = 1,
  WAITING = 2,
  ACTIVE = 3,
  DELETED = 4,
}
export enum RiskType {
  ALL = 0,
  FINANCIAL_RISK = 1,
  INTEREST_RATE_RISK = 2,
  COUNTRY_RISK = 3,
  SOCIAL_RISK = 4,
  ENVIRONMENTAL_RISK = 5,
  OPERATIONAL_RISK = 6,
  MANAGEMENT_RISK = 7,
  LEGAL_RISK = 8,
  COMPETITION_RISK = 9,
  POLITICAL_REGULATORY_RISK = 10,
}
export enum BANKS {
  OCB = 'Orient Commercial Joint Stock Bank (OCB)',
  ACB = 'Asia Commercial Bank (ACB)',
  TP_BANK = 'Tien Phong Commercial Joint Stock Bank (TP Bank)',
  HANOI_BANK = 'Hanoi Building Joint-stock Commercial Bank',
  MARITIME_BANk = 'Maritime Commercial Joint Stock Bank (Maritime Bank)',
  SACOMBANK = 'Sai Gon Thuong Tin Commercial Joint-stock Bank (Sacombank)',
  DONG_A_BANK = 'Eastern Asia Commercial Joint Stock Bank (DongA Bank)',
  EXIM_BANK = 'Vietnam Export – Import Commercial Joint Stock Bank (Eximbank)',
  NAM_A_BANK = 'Nam A Commercial Joint Stock Bank (Nam A Bank)',
  SAIGON_BANK = 'Saigon Bank for Industry & Trade (Saigon Bank)',
  VP_BANK = 'Vietnam Prosperity Joint Stock Commercial Bank (VP Bank)',
  TECHCOM_BANK = 'Viet Nam Technological and Commercial Joint Stock Bank (Techcombank)',
  MB_BANK = 'Military Commercial Joint Stock Bank (MB Bank)',
  BAC_A_BANK = 'Bac A Commercial Joint Stock Bank (Bac A Bank)',
  VID = 'Vietnam International Commercial Joint Stock Bank (VIB)',
  SE_A_BANK = 'Southeast Asia Commercial Joint Stock Bank (SeA Bank)',
  HD_BANK = 'Housing development Commercial Joint Stock Bank (HDBank)',
  VIET_CAPITAL_BANK = 'Viet Capital Commercial Joint Stock Bank (Viet Capital Bank)',
  LIEN_VIET_BANK = 'LienViet Post Commercial Joint Stock Bank',
  ME_KONG_BANK = 'Mekong Development Joint Stock Commercial Bank',
  BAO_VIET_BANK = 'Bao Viet Joint Stock Commercial Bank',
  PHUONG_TAY_BANK = 'Western Bank (Phuong Tay Bank)',
  PV_BANK = 'Viet Nam Public Bank (PVcomBank)',
}
